name: 'Notify of workflow run conclusion'

# Workflow_run full payload example
# https://github.community/t/workflow-run-full-payload-example/195854

on:
  workflow_run:
    workflows:
      - 'CI'
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT"
      - name: üí¨ Notify Telegram of workflow run FAILURE
        # https://github.com/appleboy/telegram-action
        uses: appleboy/telegram-action@v1.0.0
        # This is a container action, so it must run on Linux (it would fail if
        # `runs-on` is either `windows-latest` or `macOS-latest`)
        # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction
        # https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          # https://core.telegram.org/bots/api#formatting-options
          message: |
            <b>‚ö†Ô∏è GitHub workflow failure üíî</b>

            Repository: <a href="${{ github.event.repository.html_url }}">${{ github.event.repository.full_name }}</a>

            Workflow: <a href="${{ github.event.workflow_run.html_url }}">${{ github.event.workflow_run.name }}</a>

            Workflow Run ID: <a href="${{ github.event.workflow_run.html_url }}?check_suite_focus=true">${{ github.event.workflow_run.id }}</a>

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: üí¨ Notify Telegram of workflow run SUCCESS
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>‚úÖ GitHub workflow success üíñ</b>

            Repository: <a href="${{ github.event.repository.html_url }}">${{ github.event.repository.full_name }}</a>

            Workflow: <a href="${{ github.event.workflow_run.html_url }}">${{ github.event.workflow_run.name }}</a>

            Workflow Run ID: <a href="${{ github.event.workflow_run.html_url }}?check_suite_focus=true">${{ github.event.workflow_run.id }}</a>
